[project]
name = "personal-cookiecutter-templates"
version = "1.0.0"
description = "A collection of personal cookiecutter templates for data science projects."
authors = [
    { name = "Giuseppe Minardi", email = "giuseppe.minardi95@gmail.com" },
]
readme = "README.md"
keywords = ["statistics", "analysis", "data-science"]


[tool.ruff]
# Set the maximum line length to 88 (black's default)
line-length = 88


# Enable additional rules beyond the defaults
select = [
    "D",    # pydocstyle
    "E",    # pycodestyle errors
    "F",    # Pyflakes
    "B",    # flake8-bugbear
    "PD",   # pandas-vet
    "I",    # isort
    "N",    # pep8-naming
    "SIM",
    "Q",
    "E305",
    "C90"
]

# Ignore specific rules that are too restrictive for data science
ignore = [
    "E501",    # Line too long (handled by line-length setting)
]

# Exclude common data science directories and files
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
    "data/",
    "notebooks/archive/",
]

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.ruff.per-file-ignores]
# Ignore import rules in __init__.py files
"__init__.py" = [
    "F401", 
    "F403", 
    "D104",
]
# More lenient rules for test files
"tests/**" = ["S101", "PLR2004", "SLF001"]
# More lenient rules for scripts and exploratory files
"scripts/**" = ["T201", "S101", "PLR2004"]
"explore/**" = ["T201", "S101", "PLR2004", "B018"]

[tool.ruff.isort]
# Configure import sorting for data science
known-first-party = ["src"]
section-order = [
    "future",
    "standard-library", 
    "third-party",
    "data-science",
    "first-party",
    "local-folder"
]

[tool.ruff.isort.sections]
# Group common data science libraries together
"data-science" = [
    "numpy",
    "pandas", 
    "matplotlib",
    "seaborn",
    "plotly",
    "sklearn",
    "scipy",
    "statsmodels",
    "xgboost",
    "lightgbm",
    "catboost",
    "tensorflow",
    "torch",
    "transformers",
]

"visualization" = [
    "matplotlib.pyplot",
    "seaborn",
]

[tool.ruff.flake8-import-conventions]
# Standard aliases for data science libraries
[tool.ruff.flake8-import-conventions.aliases]
"matplotlib.pyplot" = "plt"
"numpy" = "np"
"pandas" = "pd"
"seaborn" = "sns"
"sklearn" = "sk"
"tensorflow" = "tf"
"torch" = "torch"
"pymc" = "pm"
"arviz" = "az"
"statsmodels" = "sm"


[tool.ruff.format]
# Use single quotes for strings
quote-style = "double"
# Indent with spaces
indent-style = "space"
# Respect magic trailing comma
skip-magic-trailing-comma = false
# Automatically detect line ending
line-ending = "auto"
docstring-code-format = true
docstring-code-line-length = 88