name: Build LaTeX Report

on:
  push:
    branches: [ main ]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required to commit the PDF back to the repo
    container:
      image: texlive/texlive:latest-full

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install LaTeX packages
        run: |
          apt-get update
          apt-get install -y --no-install-recommends git
          tlmgr update --self
          tlmgr install fontawesome5 fourier babel-english subcaption adjustbox booktabs xcolor titlesec titletoc csquotes hyperref listings sidecap

      - name: Compile LaTeX document (1st pass)
        working-directory: reports
        run: xelatex -interaction=nonstopmode -file-line-error report.tex

      - name: Compile LaTeX document (2nd pass)
        working-directory: reports
        run: xelatex -interaction=nonstopmode -file-line-error report.tex

      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: Statistical_Report_PDF
          path: reports/report.pdf

      - name: Create output directory and copy PDF
        run: |
          mkdir -p output
          cp reports/report.pdf output/report.pdf
          cp reports/report.pdf output/report_latest.pdf

      - name: Commit PDF to repository
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git config --global --add safe.directory "${GITHUB_WORKSPACE}"
          git add reports/report.pdf output/*
          git diff --staged --quiet || git commit -m "Update compiled report [skip ci]"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push
