name: ty type-check

on:
  pull_request:
    paths:
      - 'src/**'

jobs:
  type-check:
    name: Run Astral ty type checker
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install uv (Astral tooling)
        run: |
          python -m pip install --upgrade pip
          pip install uv

      - name: Install ty via uv
        run: uvx install ty

      - name: Verify ty version
        run: ty --version || uvx ty --version

      - name: Run ty type check on src/
        run: |
          uvx ty check src/

      - name: Archive diagnostics (optional)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: ty-diagnostics
          path: src/  # You can tailor this path if ty outputs files elsewhere